//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BangLuong
    {
        public int BangLuongID { get; set; }
        public int NhanVienID { get; set; }
        public int Thang { get; set; }
        public int Nam { get; set; }
        public decimal LuongCoBan { get; set; }
        public Nullable<decimal> Thuong { get; set; }
        public Nullable<decimal> KhauTru { get; set; }
        public Nullable<decimal> TongLuong { get; set; }
        public Nullable<int> NgayCong { get; set; }
        public Nullable<int> GioTangCa { get; set; }
        public Nullable<decimal> PhuCap { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
