//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaoCao
    {
        public int BaoCaoID { get; set; }
        public int NhanVienID { get; set; }
        public Nullable<int> DuAnID { get; set; }
        public Nullable<int> ThanhToanID { get; set; }
        public string NoiDung { get; set; }
        public System.DateTime NgayBaoCao { get; set; }
    
        public virtual DuAn DuAn { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual ThanhToan ThanhToan { get; set; }
    }
}
