//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanLyXayDungEntities2 : DbContext
    {
        public QuanLyXayDungEntities2()
            : base("name=QuanLyXayDungEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BangLuong> BangLuongs { get; set; }
        public DbSet<BaoCao> BaoCaos { get; set; }
        public DbSet<ChiTietDonDatHang> ChiTietDonDatHangs { get; set; }
        public DbSet<DonDatHang> DonDatHangs { get; set; }
        public DbSet<DuAn> DuAns { get; set; }
        public DbSet<HopDong> HopDongs { get; set; }
        public DbSet<KhachHang> KhachHangs { get; set; }
        public DbSet<Kho> Khoes { get; set; }
        public DbSet<NguoiDung> NguoiDungs { get; set; }
        public DbSet<NhaCungCap> NhaCungCaps { get; set; }
        public DbSet<NhanVien> NhanViens { get; set; }
        public DbSet<PhanCong> PhanCongs { get; set; }
        public DbSet<ThanhToan> ThanhToans { get; set; }
        public DbSet<VatTu> VatTus { get; set; }
    }
}
