//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonDatHang
    {
        public DonDatHang()
        {
            this.ChiTietDonDatHangs = new HashSet<ChiTietDonDatHang>();
            this.Khoes = new HashSet<Kho>();
            this.ThanhToans = new HashSet<ThanhToan>();
        }
    
        public int DonDatHangID { get; set; }
        public int NhaCungCapID { get; set; }
        public int NhanVienID { get; set; }
        public System.DateTime NgayDat { get; set; }
        public string TrangThai { get; set; }
    
        public virtual ICollection<ChiTietDonDatHang> ChiTietDonDatHangs { get; set; }
        public virtual NhaCungCap NhaCungCap { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual ICollection<Kho> Khoes { get; set; }
        public virtual ICollection<ThanhToan> ThanhToans { get; set; }
    }
}
