//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DuAn
    {
        public DuAn()
        {
            this.BaoCaos = new HashSet<BaoCao>();
            this.Khoes = new HashSet<Kho>();
            this.PhanCongs = new HashSet<PhanCong>();
            this.ThanhToans = new HashSet<ThanhToan>();
        }
    
        public int DuAnID { get; set; }
        public string TenDuAn { get; set; }
        public Nullable<int> KhachHangID { get; set; }
        public Nullable<int> HopDongID { get; set; }
        public Nullable<System.DateTime> NgayBatDau { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
        public string TienDo { get; set; }
        public byte[] HinhAnhDuAn { get; set; }
    
        public virtual ICollection<BaoCao> BaoCaos { get; set; }
        public virtual HopDong HopDong { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        public virtual ICollection<Kho> Khoes { get; set; }
        public virtual ICollection<PhanCong> PhanCongs { get; set; }
        public virtual ICollection<ThanhToan> ThanhToans { get; set; }
    }
}
