//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HopDong
    {
        public HopDong()
        {
            this.DuAns = new HashSet<DuAn>();
        }
    
        public int HopDongID { get; set; }
        public string MaHopDong { get; set; }
        public string TenHopDong { get; set; }
        public int KhachHangID { get; set; }
        public Nullable<int> DuAnID { get; set; }
        public System.DateTime NgayKy { get; set; }
        public decimal GiaTriHopDong { get; set; }
        public string NoiDungYeuCau { get; set; }
        public string ThoiHanThiCong { get; set; }
        public string DieuKhoanThanhToan { get; set; }
        public string TrangThai { get; set; }
        public byte[] FileHopDong { get; set; }
    
        public virtual ICollection<DuAn> DuAns { get; set; }
        public virtual KhachHang KhachHang { get; set; }
    }
}
