//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhachHang
    {
        public KhachHang()
        {
            this.DuAns = new HashSet<DuAn>();
            this.HopDongs = new HashSet<HopDong>();
        }
    
        public int KhachHangID { get; set; }
        public string HoTenKH { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string DiaChi { get; set; }
        public byte[] AnhDaiDien { get; set; }
    
        public virtual ICollection<DuAn> DuAns { get; set; }
        public virtual ICollection<HopDong> HopDongs { get; set; }
    }
}
