//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kho
    {
        public int KhoID { get; set; }
        public Nullable<int> VatTuID { get; set; }
        public string LoaiGiaoDich { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<System.DateTime> NgayGiaoDich { get; set; }
        public Nullable<int> DuAnID { get; set; }
        public Nullable<int> DonDatHangID { get; set; }
        public int NhanVienID { get; set; }
    
        public virtual DonDatHang DonDatHang { get; set; }
        public virtual DuAn DuAn { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual VatTu VatTu { get; set; }
    }
}
