//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanCong
    {
        public int PhanCongID { get; set; }
        public Nullable<int> DuAnID { get; set; }
        public Nullable<int> NhanVienID { get; set; }
        public string NhiemVu { get; set; }
        public Nullable<System.DateTime> NgayBatDau { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
    
        public virtual DuAn DuAn { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
