//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThanhToan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ThanhToan()
        {
            this.BaoCaos = new HashSet<BaoCao>();
        }
    
        public int ThanhToanID { get; set; }
        public System.DateTime NgayThanhToan { get; set; }
        public decimal SoTien { get; set; }
        public string HinhThuc { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> DuAnID { get; set; }
        public Nullable<int> DonDatHangID { get; set; }
        public int NhanVienID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BaoCao> BaoCaos { get; set; }
        public virtual DonDatHang DonDatHang { get; set; }
        public virtual DuAn DuAn { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
